TOKEN: 7082403269:AAED6kX3ak2IuJjhCzoVCWxhUH1ELC-o6xo

rcp_client:
  host: localhost
  queues:
    brain_queue: brain_queue
    xray_queue: xray_queue
    first_check_queue: first_check
    second_check_queue: second_check