TOKEN: your bot token

rpc_client:
  host: your hostname
  queues:
    brain_queue: brain_queue
    xray_queue: xray_queue
    first_check_queue: first_check
    second_check_queue: second_check
    fullcheck_queue: fullcheck

users_db:
  host: 'your postgres host'
  port: 'your postgres port'
  user: 'your postgres username'
  password: 'your postgres password'
  database: 'your database name'